<?php

namespace ADAL;

use Exception;

class AdalException extends Exception
{
    /**
     * Gets the protocol error code returned by the service or generated by client. This is the code you can rely on for exception handling.
     * @var string
     */
    public $ErrorCode;

    /**
     * [__construct description]
     */
    public function __construct(string $errorCode = null)
    {
        if ($errorCode == null) {
            $errorCode = AdalError::UNKNOWN;
        }
        $this->ErrorCode = $errorCode;
    }
}
